Fixing launch
coast-team/mute pull request #111
Opened 2022-01-17 14:52 UTC by BaptisteHubert

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
New dockerfile for deployment on the team server, also added a res folder for documentation

2022-01-17 17:41 UTC, rigelk commented
I don't think the documentation should sit within the repository, but rather in the wiki.

2022-01-18 13:05 UTC, rigelk requested changes

2022-01-18 13:05 UTC, rigelk commented on package.json
> +      "path": "dis-t/*es2015*.js"
why the change?

2022-01-18 13:05 UTC, rigelk commented on scripts/get-assets-w.bat
> +REM - Script visant à récupérer les assets javascripts utilisés pour le build de l'application.
comments should be in english

2022-01-18 13:05 UTC, rigelk commented on scripts/get-assets-w.bat
> +    echo "Le fichier %~1 existe déjà"
same

2022-01-18 13:05 UTC, rigelk commented on tsconfig.json
> +    "emitDecoratorMetadata": false,
is this not is a leftover from debug?

2022-01-18 13:05 UTC, rigelk commented on Dockerfile
> +#Lancement de Mute
comments should be in english

2022-01-18 13:05 UTC, rigelk commented on Dockerfile
> +#Build de mute
comments should be in english

2022-01-20 10:01 UTC, BaptisteHubert commented
I have taken the advices in consideration and fixed the files accordingly. Tested with docker-compose and the application runs locally. The signaling server also works (test with different tab).

2022-01-20 11:57 UTC, rigelk requested changes
the `start.sh` script should be placed in the eponym directory. Apart from that, LGTM!

2022-01-20 11:57 UTC, rigelk commented on src/environments/environment.prod.ts
> +const host = 'localhost'
```suggestion
const host = 'localhost' // FIXME: interpolation at build time required
```

2022-01-20 11:57 UTC, rigelk commented on src/environments/environment.ts
> +const host = 'coedit.re'
```suggestion
```

2022-01-20 13:35 UTC, merged